version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: todoslist
    restart: unless-stopped
    container_name: todoslist-app
    depends_on:
      - db
    ports:
      - 9000:9000
    working_dir: /var/www/
    volumes:
      - ./todos-app:/var/www
    networks:
      - todoslist

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: todoslist
      MYSQL_ROOT_PASSWORD: todoslist
      MYSQL_PASSWORD: todoslist
      MYSQL_USER: customer
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - todoslist

  nginx:
    image: nginx:alpine
    container_name: todoslist-nginx
    restart: unless-stopped
    depends_on:
      - db
      - app
    ports:
      - 8000:80
    volumes:
      - ./todos-app:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - todoslist
      
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql # ${DB_HOST}
      - PMA_PORT=3306 #${DB_PORT}
      - PMA_USER=customer #${DB_USERNAME}
      - PMA_PASSWORD=todoslist #${DB_PASSWORD}
    networks:
      - todoslist
 
networks:
  todoslist:
    driver: bridge
